language: python
python:
  - "2.7"
install:
  - pip install -r requirements/dev.txt
# command to run tests
before_script:
  - cp config.py.test config.py
  - psql -c 'create database mm;' -U postgres
  - ./manage.py db init
  - ./manage.py db migrate
  - ./manage.py db upgrade
script: nosetests
after_success:
  coveralls


notifications:
  irc:
    channels: "chat.freenode.net#multiverseminer"
    on_success: change # default: always
    on_failure: change # default: always
    template:
      - "%{repository} (%{commit}) : %{message} "
      - "Build details: %{build_url}"
